# Generated by Django 3.2.11 on 2022-01-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrescue', '0002_auto_20220118_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='address',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='foster',
            name='address',
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='state',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='street_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='zipcode',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='street_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='zipcode',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='foster',
            name='city',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='foster',
            name='state',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='foster',
            name='street_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foster',
            name='zipcode',
            field=models.IntegerField(default=False),
        ),
    ]
