# Generated by Django 3.2.11 on 2022-01-24 17:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('petrescue', '0004_auto_20220123_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='foster',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health_notes',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
