# Generated by Django 3.2.11 on 2022-01-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrescue', '0005_auto_20220124_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
