# Generated by Django 3.2.11 on 2022-01-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petrescue', '0006_auto_20220125_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='foster_adopt',
        ),
        migrations.AddField(
            model_name='agency',
            name='pet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='petrescue.pet'),
        ),
        migrations.AddField(
            model_name='pet',
            name='animal_sex',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F')], default='male', max_length=25),
        ),
    ]
