# Generated by Django 3.2.11 on 2022-01-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrescue', '0007_auto_20220126_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='pet',
        ),
    ]
