# Generated by Django 3.2.11 on 2022-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrescue', '0008_remove_agency_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_photo',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='animal_sex',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vac_status',
        ),
        migrations.AddField(
            model_name='pet',
            name='age_group',
            field=models.CharField(choices=[('Puppy', 'Puppy'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], default='Puppy', max_length=15),
        ),
        migrations.AddField(
            model_name='pet',
            name='current_on_vac',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='good_with_cats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='good_with_dogs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='good_with_kids',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='heart_worm_positive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='Male', max_length=25),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large,', 'Large')], default='Medium', max_length=15),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Adopted', 'Adopted')], default='Available', max_length=25),
        ),
    ]
