# Generated by Django 3.2.11 on 2022-01-30 21:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('petrescue', '0012_auto_20220130_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='tags',
        ),
        migrations.AddField(
            model_name='agency',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='agency',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='agency',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pet',
            name='health_concerns',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agency',
            name='about_us',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='agency',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='agency',
            name='street_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agency',
            name='street_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agency',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='num_adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='num_children',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='pet_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='petrescue.pet'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.TextField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Denied', 'Denied'), ('Open', 'Open')], default='Open'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='street_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='street_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foster',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='foster',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='foster',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='foster',
            name='street_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='foster',
            name='street_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='foster',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_group',
            field=models.CharField(blank=True, choices=[('Puppy', 'Puppy'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pet',
            name='current_on_vac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F')], max_length=25),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
