# Generated by Django 3.2.11 on 2022-01-30 22:40

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('petrescue', '0013_auto_20220130_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='foster_info',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='health_concerns',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='foster',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='foster',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='pet',
            name='foster_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='num_adults',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='num_children',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='foster',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
