# Generated by Django 3.2.11 on 2022-01-31 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petrescue', '0015_auto_20220131_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='heart_worm_positive',
            new_name='heartworm_positive',
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_owner',
            field=models.CharField(blank=True, max_length=150, verbose_name='rescue owner'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='rescue organization'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='street_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='street address'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='street_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='street address line 2'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='adopt_reason',
            field=models.TextField(blank=True, choices=[('Companion', 'Companion'), ('Guard_Dog', 'Guard_Dog'), ('Breeding', 'Breeding'), ('Other', 'Other')], verbose_name="reason you're interested in adopting a pet"),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ages_children',
            field=models.TextField(blank=True, verbose_name='ages of children in the home'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='current_residence',
            field=models.TextField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Condo', 'Condo')], verbose_name='type of home'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='num_adults',
            field=models.CharField(blank=True, max_length=50, verbose_name='number of adults in the home'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='num_children',
            field=models.CharField(blank=True, max_length=50, verbose_name='number of children in the home'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='other_pets',
            field=models.BooleanField(default=False, verbose_name='do you currently have any other pets?'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='other_pets_desc',
            field=models.TextField(blank=True, verbose_name='if yes, please list them below'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='pet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petrescue.pet', verbose_name="name of pet you're applying for"),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='primary phone'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='primary_owner',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name of intended primary owner'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='street_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='street address'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='street_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='street address line 2'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='current_on_vac',
            field=models.BooleanField(default=False, verbose_name='up-to-date vaccinations '),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health_concerns',
            field=models.BooleanField(default=False, verbose_name='other health concerns'),
        ),
    ]
